package com.example.demo.entity;

public enum CategoryName {
    FANTASY, SCI_FI, MYSTERY, THRILLER, ROMANCE,

    PROGRAMMING, ENGLISH, SELF_HELP, BUSINESS, ACTION_AND_ADVENTURE,

    CLASSICS, COMIC, HISTORICAL, BIOGRAPHY, CHILDREN
}
